POST http://localhost:5000/api/item/add
Content-Type: application/json

{
   "title": "sid ",
   "author": "w",
   "genre": "w",
   "price": 2,
   "quantity": 4
}

###
GET http://localhost:5000/api/item
Content-Type: application/json

{
   "title": "sid ",
   "author": "w",
   "genre": "w",
   "price": 2,
   "quantity": 4
}

###
GET http://localhost:5000/api/item/64907e326a692987237b8dd8
Content-Type: application/json

{
   "title": "sid ",
   "author": "w",
   "genre": "w",
   "price": 2,
   "quantity": 4
}

###
PATCH  http://localhost:5000/api/item/64907e326a692987237b8dd8
Content-Type: application/json

{
   "title": "goku "
}

###
DELETE   http://localhost:5000/api/item/64907e326a692987237b8dd8
Content-Type: application/json

{
   "title": "goku "
}